services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-controle-financeiro:latest
    container_name: api-controle-financeiro
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    env_file:
      - .env